variables :
  IMAGE_NAME : priyanshinair02/bookings
  IMAGE_TAG : bookings-1.0

build-image : 
  image : docker:20.10.16
  services :
    -docker:20.10.16-dind
  variables :
    DOCKER_TLS_CERT/DIR : "/certs"
  before_script :
    -docker logic -u $USERNAME -p $PASSWORD
  script : 
    -docker build -t $IMAGE_NAME:IMAGE_TAG
    -docker push $IMAGE_NAME:$IMAGE_TAG